version: '3.8'

services:
  db:
    container_name: db
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    image:
      postgres:15.3-alpine3.18
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - mainnetwork
  project:
    build: .
    depends_on:
      - db
    volumes:
      - ./app:/app
    networks:
      - mainnetwork

networks:
  mainnetwork: