version: '3.8'

services:
  db:
    container_name: db
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    image:
      postgres:15.3-alpine3.18
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - mainnetwork
  database_creator:
    build: ./database_creator
    depends_on:
      - db
    volumes:
      - ./database_creator:/database_creator
    networks:
      - mainnetwork
  # database_creator:
  #   build: ./nn
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./nn:/nn
  #   networks:
  #     - mainnetwork

networks:
  mainnetwork: