version: '3.8'

services:
  db:
    container_name: db
    ports:
      - 5433:${POSTGRES_PORT}
    image:
      postgres:15.3-alpine3.18
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - mainnetwork
    logging:
      driver: none
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
  app:
    container_name: app
    build: ./app
    command: python main.py
    depends_on:
      - db
    volumes:
      - ./app:/app
    networks:
      - mainnetwork
    environment:
      FLASK_APP: main.py
      FLASK_ENV: development
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
      HOST: "${HOST}"
      NAME: "${NAME1}"
    expose:
      - 5000
  nginx:
    container_name: nginx
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    depends_on:
      - app
    networks:
      - mainnetwork
  # neural_network:
  #   container_name: nn
  #   build: ./nn
  #   command: python main.py
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./nn:/nn
  #     - /tmp/.X11-unix:/tmp/.X11-unix
  #   networks:
  #     - mainnetwork
  #   environment:
  #     POSTGRES_USER: "${POSTGRES_USER}"
  #     POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  #     PORT: "${PORT}"
  #     HOST: "${HOST}"
  #     NAME1: "${NAME1}"
  #     NAME2: "${NAME2}"
  #   runtime: nvidia

networks:
  mainnetwork: